### ISSUE TITLE
Screenshots & demo & upload

### ISSUE THREAD

**Issue by petrk94** [altesack/gencms#1]
Hello,

interesting system, I would like to try, but mysql database from my hoster is not the latest one.
Can you show how the system work?
Thanks

**Comment by altesack** [comment]
Hi! I'm not sure what for you need it. This system is not ready for production 
Here are few screenshots from my local
https://screenshots.firefox.com/SQ1XCBc80vC1lbYY/127.0.0.1
https://screenshots.firefox.com/NMvLicYuN2fwpy9x/127.0.0.1
https://screenshots.firefox.com/cKHmjT0ua90fzbXu/127.0.0.1
https://screenshots.firefox.com/YRysjFoAggZZMD16/127.0.0.1
https://screenshots.firefox.com/ufBKh8RbtKdEFBRH/127.0.0.1

All the data is deployed from gedcom files import:

`altesack@inspiron ~/PHP7/my_family_book $ php artisan gencms:importgedcom ./gedcomfiles/EnglishTudorHouse.ged 

 Parsing is done. Keep old data in DB? (yes/no) [no]:
 > n

 443/443 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
110 seconds taken to handle 120244 bytes. 1093.13 bytes per second
altesack@inspiron ~/PHP7/my_family_book $ 
`

**Comment by petrk94** [comment]
ok, thanks, I just wanted to see how the UI is looking.
